name: Docker Image CI

on:
  push:
    branches: '*'
    tags: '*'
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Docker Build
      run: make docker-build

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
      if: startsWith(github.ref, 'refs/tags/')

    - name: Docker Push
      run: |
        make docker-deploy
      if: startsWith(github.ref, 'refs/tags/')