name: Go

on:
  push:
    branches: ['*']
    tags: ['*']

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.23'

    - name: Build & Test
      run: make